---
title: "Animating Data Visualization"
output: github_document
---


Setting up environment

For the sake of keep things simple for this exercise, I am taking top ten countries for 2016 and see the behavior from 1985...

```{r}
library(RColorBrewer)
library(tidyverse)
library(stringr)
library(lattice)
library(animation)
options(scipen=999)
ffmpeg_path <- "C:/Program Files/ffmpeg/bin/ffmpeg.exe"
ffmpeg_opts <- "-r 15 -pix_fmt yuv420p"
# Animation parameters
ani.options(
  interval = 1, #0.067,
  ani.width = 640,
  ani.height = 480)


palette <- brewer.pal(10,"Set3")

suicides_dataset <- read.csv("../data/SuicideRatesOverview1985-to-2016.csv")

top10_suicides_countries <- suicides_dataset %>%
  filter(year == 2016) %>%
  select(country, year, suicides.100k.pop, gdp_for_year....) %>%
  group_by(year, country, gdp_for_year....) %>%
  summarize(suicides.100k.pop = sum(suicides.100k.pop)/n())%>%
  ungroup() %>%
  mutate(gdp_for_year.... =as.numeric(str_replace_all(gdp_for_year....,",","")))%>%
  arrange(desc(suicides.100k.pop)) %>%
  top_n(10) %>%
  mutate(color = row_number())

```


Let's try our chart for 2016

```{r}

plot(
  x = top10_suicides_countries$gdp_for_year....,
  y = top10_suicides_countries$suicides.100k.pop,
  col = palette[top10_suicides_countries$color],
  pch = 19,
  cex = 2,
  main = "Top 10 Countries by Suicides (2016)",
  xlab = "GDP",
  ylab = "Suicide per 100k",
  sub = top10_suicides_countries$year)

legend(
  x = "topright",
  as.character(top10_suicides_countries$country),
  col = palette[top10_suicides_countries$color],
  pch = 19,
  cex = 1)

```

Delete unneeded columns
```{r}
top10_suicides_countries$year <- NULL
top10_suicides_countries$gdp_for_year.... <- NULL
top10_suicides_countries$suicides.100k.pop <- NULL

```


## Animation

### Animation to tell a story

#### Animation functions


```{r}
#browser()
#Get the required data

top10_suicide_subset <- suicides_dataset %>%
  filter(country %in% top10_suicides_countries$country) %>%
  select(year, country,  gdp_for_year...., suicides.100k.pop) %>%
  mutate(gdp_for_year.... = as.numeric(str_replace_all(gdp_for_year....,",",""))/1000000) %>%
  group_by(year, country,  gdp_for_year....) %>%
  summarize(suicides.100k.pop = sum(suicides.100k.pop)/n()) %>%
  ungroup() %>%
  merge(top10_suicides_countries, by = "country") 
  

x_max_value = max(top10_suicide_subset$gdp_for_year....) 
x_min_value = min(top10_suicide_subset$gdp_for_year....)

animate_suicide_plot <- function(){
  for(i in 1985:2016){
    year <- i
    
    year_subset <- top10_suicide_subset %>%
      filter(year == i)
    
    plot(
      x = year_subset$gdp_for_year....,
      y = year_subset$suicides.100k.pop,
      col = palette[year_subset$color],
      pch = 19,
      cex = 2,
      xlim = c(x_min_value, x_max_value),
      ylim = c(0,80),
      main = "Top 10 Countries by Suicide in 2016 through time",
      xlab = "GDP ($M)",
      ylab = "Suicide per 100k",
      sub = year_subset$year)
   
    
    
    legend(
      x = "topright",
      as.character(year_subset$country),
      col = palette[year_subset$color],
      pch = 19,
      cex = 1)
    
    print(plot)
  }
}

```


#### Animation package

```{r eval=FALSE}

# Save the animation as a video
saveVideo(
  expr = animate_suicide_plot(),
  video.name = "../figs/Suicide_1985-2016.mp4",
  ffmpeg = ffmpeg_path,
  other.opts = ffmpeg_opts)

```

### Animation to Improve perspective

```{r}
load("../rda/apps_versions_dataset.rda")
apps_versions_dataset %>%
  filter(Type == "Paid" & !is.na(Rating)) %>%
  cloud(
    x = PriceNumeric ~ Reviews * Rating,
    type = c("p","h"),
    pch = 16,
    main = "Reviews, Rating, and Price",
    xlab = "Reviews",
    ylab = "Rating",
    zlab = "Price")

```

```{r eval=FALSE}
filtered_apps_versions_dataset <- apps_versions_dataset %>%
  filter(Type == "Paid" & !is.na(Rating))

animate_apps_data <- function(){
  for (i in 1:360) {
        plot <- cloud(
          x = Price ~ Rating * Reviews,
          data = filtered_apps_versions_dataset,
          type = c("p","h"),
          pch = 16,
          main = "Reviews, Rating, and Price",
          xlab = "Reviews",
          ylab = "Rating",
          zlab = "Price",
          R.mat = diag(4),
          screen = list(
           z = i,
           y = 0,
           x = -60))
          
      print(plot)
  }
}


saveVideo(
  expr = animate_apps_data(),
  video.name = "../figs/Apps_Data_Animated.mp4",
  ffmpeg = ffmpeg_path,
  other.opts = ffmpeg_opts)
```



### Animation to Capture Attention

```{r eval=FALSE}
suicide_rates_dataset <- read.csv("../data/SuicideRatesOverview1985-to-2016.csv")
map <- map_data("world")

suicide_dataset <- suicide_rates_dataset %>%
  left_join(map, by =c("country" = "region")) %>%
  select(
    country,
    Longitude = long,
    Latitude = lat,
    Group = group,
    Order = order,
    Suicides100k = suicides.100k.pop) %>%
  arrange(Order) %>%
  as.data.frame()
```


```{r eval=FALSE}
animate_world <- function(){
  for(i in -180:180){
    plot <- ggplot(data = suicide_dataset) +
      borders(
        database = "world",
        colour = "grey60",
        fill = "grey90") +
      xlab("") +
      ylab("") +
      theme( panel.background = element_blank(),
          axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank()) +
      coord_map(
        projection = "ortho",
        orientation = c(0,i,0)) +
      geom_polygon(
        aes(
         x = Longitude ,
         y = Latitude,
         group = Group,
         fill = Suicides100k),
        colour = "grey60") +
      scale_fill_gradient(
        low = "white",
        high = "red",
        guide = FALSE) +
      ggtitle("Count of Suicides by Country") +
      labs(color = "Suicides")
      
    print(plot)
  } 
}

saveVideo(
  expr = animate_world(),
  video.name = "../figs/world.mp4",
  ffmpeg = ffmpeg_path)

```

